- name: restart for {{ app }}
  hosts: all
  user: root
  gather_facts:  false
  become_user: root
  vars_files:
    - vars.yaml
  tasks:



      #重启服务
      - name: restart for {{ app }}
        systemd:  name={{ app }} state=restarted
        register: result
      - name: Show debug info
        debug: var=result verbosity=0

